steps:
  - name: ":rspec:"
    command: "scripts/ci/setup.sh && scripts/ci/parallel_specs.sh"
    artifact_paths: "log/**/*.log"
    parallelism: 5
    plugins:
      - docker#v3.0.0:
          image: "ruby:2.7.2"
          workdir: "/app"
          env:
            - KNAPSACK_GENERATE_REPORT=true
            - BUILDKITE_PARALLE_JOB
            - BUILDKITE_PARALLEL_JOB_COUNT
            - BUILDKITE_BUILD_ID
            - BUILDKITE_BUILD_NUMBER
          volumes:
            - ./knapsack_rspec_report.json:/app/knapsack_rspec_report.json
            - ./log:/app/log