steps:
  - name: ":rspec:"
    command: ".buildkite/scripts/ci/setup.sh && .buildkite/scripts/ci/parallel_specs.sh"
    artifact_paths: "log/**/*.log"
    parallelism: 5
    key: "ruby"
    plugins:
      - docker#v3.0.0:
          environment:
            - KNAPSACK_GENERATE_REPORT=true
            - BUILDKITE_PARALLEL_JOB
            - BUILDKITE_PARALLEL_JOB_COUNT
            - BUILDKITE_BUILD_ID
            - BUILDKITE_BUILD_NUMBER
          image: "ruby:2.7.2"
          volumes:
            - ./knapsack_rspec_report.json:/app/knapsack_rspec_report.json
            - ./log:/app/log
          workdir: "/app"
  - wait

  - label: "aggregate logs"
    command: ".buildkite/scripts/ci/log_aggregator.rb"
    artifact_paths: "log/**/*.json"
    key: aggregate
    plugins:
      - docker#v3.0.0:
          environment:
            - BUILDKITE_API_TOKEN
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_ORGANIZATION_SLUG
            - BUILDKITE_PIPELINE_SLUG
            - FOO="ODNlMGMzYWIzMDI2Y2ZmZTJkYWU2ZmQ3ZmE2ZDhlYTllZmM3Y2Q3Mg==\n"
          image: "ruby:2.7.2"
          volumes:
            - ./log:/app/log
          workdir: "/app"